### ISSUE TITLE
Hey. Windows permissions issues 

### ISSUE THREAD

**Issue by twobob** [JackismyShephard/ultimate-rvc#114]
Attempting to upload a wav locally on windows results in the following - somewhat dense - error

`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\gradio\route_utils.py", line 761, in __call__
    await self.app(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 74, in app
    await response(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\responses.py", line 348, in __call__
    await self._handle_simple(send, send_header_only)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\responses.py", line 372, in _handle_simple
    async with await anyio.open_file(self.path, mode="rb") as file:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\anyio\_core\_fileio.py", line 178, in open_file
    fp = await to_thread.run_sync(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\repo\\ultimate-rvc\\temp\\6f6da86c8417a7f6a72db07d06fe1085a265c10c10cb7b52671c1de386de1cda\\vocals.wav'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\gradio\route_utils.py", line 761, in __call__
    await self.app(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 74, in app
    await response(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\responses.py", line 348, in __call__
    await self._handle_simple(send, send_header_only)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\responses.py", line 377, in _handle_simple
    await send({"type": "http.response.body", "body": chunk, "more_body": more_body})
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\middleware\errors.py", line 162, in _send
    await send(message)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 510, in send
    output = self.conn.send(event=h11.EndOfMessage())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\h11\_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\h11\_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length`

![image](https://github.com/user-attachments/assets/48b4ac99-4aa1-447a-b84e-28d412ecade5)

Any clues?

**Comment by twobob** [comment]
![image](https://github.com/user-attachments/assets/ad3413fa-c7ad-4362-b565-13634c8b07cd)

Hmm the thot plickens.

**Comment by twobob** [comment]
this gives

`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\repo\ultimate-rvc\dependencies\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\shutil.py", line 847, in move
    os.rename(src, real_dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\new\\AppData\\Local\\Temp\\tmpkc5xkjao' -> 'D:\\repo\\ultimate-rvc\\temp\\6f6da86c8417a7f6a72db07d06fe1085a265c10c10cb7b52671c1de386de1cda\\vocals.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\gradio\route_utils.py", line 767, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\gradio\route_utils.py", line 783, in simple_response
    await self.app(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\routing.py", line 74, in app
    await response(scope, receive, send)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\responses.py", line 158, in __call__
    await self.background()
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\background.py", line 41, in __call__
    await task()
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\background.py", line 28, in __call__
    await run_in_threadpool(self.func, *self.args, **self.kwargs)
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\gradio\route_utils.py", line 686, in move_uploaded_files_to_cache
    shutil.move(file, dest)
  File "D:\repo\ultimate-rvc\dependencies\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\shutil.py", line 867, in move
    copy_function(src, real_dst)
  File "D:\repo\ultimate-rvc\dependencies\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\shutil.py", line 460, in copy2
    _winapi.CopyFile2(src_, dst_, flags)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process
Traceback (most recent call last):
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\gradio\blocks.py", line 1931, in process_api
    inputs = await self.preprocess_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\gradio\blocks.py", line 1662, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\gradio\components\audio.py", line 247, in preprocess
    processing_utils.audio_to_file(
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\gradio\processing_utils.py", line 566, in audio_to_file
    file = audio.export(filename, format=format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\pydub\audio_segment.py", line 867, in export
    out_f, _ = _fd_or_path_or_tempfile(out_f, 'wb+')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repo\ultimate-rvc\.venv\Lib\site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
         ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\repo\\ultimate-rvc\\temp\\6f6da86c8417a7f6a72db07d06fe1085a265c10c10cb7b52671c1de386de1cda\\vocals.wav'`

but! I Do get to see the file...

![image](https://github.com/user-attachments/assets/27664643-cb3a-4bff-a6d7-5cd9093ac680)

which feels a bit like progress. Anyway thought I should report.

**Comment by twobob** [comment]
![image](https://github.com/user-attachments/assets/35a8a160-b590-470a-8f14-f327582ad991)

N:B: just use the local path feature - that works !

**Comment by twobob** [comment]
This may well be moot given the above.  Relegating to known features. Feel free to Necro

**Comment by JackismyShephard** [comment]
Hey @twobob ! Sorry I didnt notice this issue before now. It looks to be related to file access rights? is it still not working?

**Comment by twobob** [comment]
It works in the way I showed finally. just using the other upload process.

The alternate upload process never worked. but it was moot since it was workaroundable. thanks

**Comment by JackismyShephard** [comment]
@twobob I understand what you mean but I am still a bit worried that you cannot use the upload local file feature. That should work and I have never had any problems with it myself. If you do happen to figure out what the problem is or have  more specific (reproducible) example please let me know 😄

**Comment by twobob** [comment]
yah I tried a whole bunch of thing to get it working. never worked (many hours of faff, perm changes and general code eyeballing).  I honestly abanoned the testing after the local thing worked.

**Comment by JackismyShephard** [comment]
@twobob that is completely fair. I appreciate you testing it out and letting me know. You are welcome to raise a new issue if you have more information that I can use for debugging
