### ISSUE TITLE
DLL load failed while importing onnx_cpp2py_export

### ISSUE THREAD

**Issue by nitrocon** [JackismyShephard/ultimate-rvc#137]
Running youre App with gitbash on python 3.12, windows 10. When trying to generate from a youtube link...

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Nitrocon\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nitrocon\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nitrocon\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\blocks.py", line 2019, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nitrocon\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\blocks.py", line 1566, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nitrocon\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nitrocon\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Nitrocon\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nitrocon\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nitrocon\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultimate_rvc\web\common.py", line 71, in _wrapped_fn
    raise gr.Error(str(e)) from e
gradio.exceptions.Error: 'DLL load failed while importing onnx_cpp2py_export: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.'

**Comment by JackismyShephard** [comment]
Hi @nitrocon ! 

Based on your error message it looks like you are missing some DLLs needed for running ONNX, but without more context it is difficult to troubleshoot the cause of the problem. I am also not able  to reproduce the error message myself.

However, there has been other bugs which have been solved in a recent update. Hence, I would encourage you to update to the latest version (using `git pull`). Also, on Windows you are supposed to run Ultimate RVC through powershell. Finally, I actually have never tested the project on Windows 10, so I technically cannot guarantee it works there. 

Let me know if you are still having problems after implementing the above suggestions 😄

**Comment by JackismyShephard** [comment]
@nitrocon Did you fix this issue? Otherwise I am going to close this issue.

**Comment by nitrocon** [comment]
Yea, it was something with different versions with the modules I think.
